[package]
name = "fe3o2"
version = "1.0.0"
description = "interview technical test"
edition = "2018"

[dependencies]
actix-web = "1.0"
serde="1.0"
serde_json="1.0"
bytes="0.4"

[build-dependencies]
vergen = "0.1"
